# Generated by Django 3.1.12 on 2021-08-31 06:26

from django.db import migrations, models
import django.utils.timezone
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['-date_added', 'name'], 'verbose_name': '用户', 'verbose_name_plural': '用户'},
        ),
        migrations.AlterField(
            model_name='channel',
            name='add_date',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建日时'),
        ),
        migrations.AlterField(
            model_name='channel',
            name='banner_logo',
            field=imagekit.models.fields.ProcessedImageField(blank=True, default='userlogos/banner.jpg', upload_to='userlogos/%Y/%m/%d', verbose_name='Banner Logo'),
        ),
        migrations.AlterField(
            model_name='channel',
            name='description',
            field=models.TextField(blank=True, help_text='description', verbose_name='简介'),
        ),
        migrations.AlterField(
            model_name='channel',
            name='friendly_token',
            field=models.CharField(blank=True, max_length=12, verbose_name='易记Token'),
        ),
        migrations.AlterField(
            model_name='channel',
            name='title',
            field=models.CharField(db_index=True, max_length=90, verbose_name='标题'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='action',
            field=models.CharField(blank=True, max_length=30, verbose_name='动作'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='method',
            field=models.CharField(choices=[('email', 'Email')], default='email', max_length=20, verbose_name='通知方法'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notify',
            field=models.BooleanField(default=False, verbose_name='已通知'),
        ),
        migrations.AlterField(
            model_name='user',
            name='advancedUser',
            field=models.BooleanField(db_index=True, default=False, verbose_name='高级用户'),
        ),
        migrations.AlterField(
            model_name='user',
            name='allow_contact',
            field=models.BooleanField(default=False, help_text='是否允许联系，将显示在个人资料页', verbose_name='是否允许联系'),
        ),
        migrations.AlterField(
            model_name='user',
            name='date_added',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='创建日时'),
        ),
        migrations.AlterField(
            model_name='user',
            name='description',
            field=models.TextField(blank=True, verbose_name='关于我'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_editor',
            field=models.BooleanField(db_index=True, default=False, verbose_name='内容编辑'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_featured',
            field=models.BooleanField(db_index=True, default=False, verbose_name='是否精选'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_manager',
            field=models.BooleanField(db_index=True, default=False, verbose_name='经理'),
        ),
        migrations.AlterField(
            model_name='user',
            name='location',
            field=models.CharField(blank=True, max_length=250, verbose_name='位置'),
        ),
        migrations.AlterField(
            model_name='user',
            name='logo',
            field=imagekit.models.fields.ProcessedImageField(blank=True, default='userlogos/user.jpg', upload_to='userlogos/%Y/%m/%d', verbose_name='头像'),
        ),
        migrations.AlterField(
            model_name='user',
            name='media_count',
            field=models.IntegerField(default=0, verbose_name='媒体数量'),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(db_index=True, max_length=250, verbose_name='全称'),
        ),
        migrations.AlterField(
            model_name='user',
            name='notification_on_comments',
            field=models.BooleanField(default=True, help_text='内容被评论时是否要收到电子邮件通知', verbose_name='评论时通知'),
        ),
        migrations.AlterField(
            model_name='user',
            name='title',
            field=models.CharField(blank=True, max_length=250, verbose_name='标题'),
        ),
    ]
