# Generated by Django 3.1.12 on 2021-08-31 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0003_auto_20201201_0712'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mediaaction',
            options={'verbose_name': '媒体动作', 'verbose_name_plural': '媒体动作'},
        ),
        migrations.AlterField(
            model_name='mediaaction',
            name='action',
            field=models.CharField(choices=[('like', '喜欢'), ('dislike', '不喜欢'), ('watch', '观看'), ('report', '报告'), ('rate', '评分')], default='watch', max_length=20, verbose_name='动作'),
        ),
        migrations.AlterField(
            model_name='mediaaction',
            name='action_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='动作时间'),
        ),
        migrations.AlterField(
            model_name='mediaaction',
            name='extra_info',
            field=models.TextField(blank=True, null=True, verbose_name='扩展信息'),
        ),
        migrations.AlterField(
            model_name='mediaaction',
            name='remote_ip',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='远程IP'),
        ),
    ]
