# Generated by Django 3.1.12 on 2021-08-31 06:26

from django.conf import settings
import django.contrib.postgres.search
from django.db import migrations, models
import django.db.models.deletion
import files.models
import imagekit.models.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210831_1426'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('files', '0002_auto_20201201_0712'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['title'], 'verbose_name': '类别', 'verbose_name_plural': '类别'},
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name': '评论', 'verbose_name_plural': '评论'},
        ),
        migrations.AlterModelOptions(
            name='encodeprofile',
            options={'ordering': ['resolution'], 'verbose_name': '编码配置', 'verbose_name_plural': '编码配置'},
        ),
        migrations.AlterModelOptions(
            name='encoding',
            options={'verbose_name': '编码', 'verbose_name_plural': '编码'},
        ),
        migrations.AlterModelOptions(
            name='language',
            options={'ordering': ['id'], 'verbose_name': '语言', 'verbose_name_plural': '语言'},
        ),
        migrations.AlterModelOptions(
            name='license',
            options={'verbose_name': '许可证', 'verbose_name_plural': '许可证'},
        ),
        migrations.AlterModelOptions(
            name='media',
            options={'ordering': ['-add_date'], 'verbose_name': '媒体', 'verbose_name_plural': '媒体'},
        ),
        migrations.AlterModelOptions(
            name='playlist',
            options={'verbose_name': '播放列表', 'verbose_name_plural': '播放列表'},
        ),
        migrations.AlterModelOptions(
            name='playlistmedia',
            options={'ordering': ['ordering', '-action_date'], 'verbose_name': '播放列表媒体', 'verbose_name_plural': '播放列表媒体'},
        ),
        migrations.AlterModelOptions(
            name='rating',
            options={'verbose_name': '评分', 'verbose_name_plural': '评分'},
        ),
        migrations.AlterModelOptions(
            name='ratingcategory',
            options={'verbose_name': '评分类别', 'verbose_name_plural': '评分类别'},
        ),
        migrations.AlterModelOptions(
            name='subtitle',
            options={'verbose_name': '字幕', 'verbose_name_plural': '字幕'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ['title'], 'verbose_name': '标签', 'verbose_name_plural': '标签'},
        ),
        migrations.RemoveField(
            model_name='encoding',
            name='media_file',
        ),
        migrations.AddField(
            model_name='encoding',
            name='encoding file',
            field=models.FileField(blank=True, max_length=500, upload_to=files.models.encoding_media_file_path, verbose_name='媒体文件'),
        ),
        migrations.AlterField(
            model_name='category',
            name='add_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='添加日时'),
        ),
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True, verbose_name='简介'),
        ),
        migrations.AlterField(
            model_name='category',
            name='is_global',
            field=models.BooleanField(default=False, help_text='全局类别或特定于用户', verbose_name='是否全局'),
        ),
        migrations.AlterField(
            model_name='category',
            name='listings_thumbnail',
            field=models.CharField(blank=True, help_text='缩略图显示在列表', max_length=400, null=True, verbose_name='列表缩略图'),
        ),
        migrations.AlterField(
            model_name='category',
            name='media_count',
            field=models.IntegerField(default=0, help_text='媒体数量统计', verbose_name='媒体数量'),
        ),
        migrations.AlterField(
            model_name='category',
            name='thumbnail',
            field=imagekit.models.fields.ProcessedImageField(blank=True, upload_to=files.models.category_thumb_path, verbose_name='缩略图'),
        ),
        migrations.AlterField(
            model_name='category',
            name='title',
            field=models.CharField(db_index=True, max_length=100, unique=True, verbose_name='标题'),
        ),
        migrations.AlterField(
            model_name='category',
            name='uid',
            field=models.UUIDField(default=uuid.uuid4, unique=True, verbose_name='UUID'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='add_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='添加日时'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=models.TextField(help_text='文本', verbose_name='文本'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='uid',
            field=models.UUIDField(default=uuid.uuid4, unique=True, verbose_name='UUID'),
        ),
        migrations.AlterField(
            model_name='encodeprofile',
            name='active',
            field=models.BooleanField(default=True, verbose_name='活动的'),
        ),
        migrations.AlterField(
            model_name='encodeprofile',
            name='codec',
            field=models.CharField(blank=True, choices=[('h265', 'h265'), ('h264', 'h264'), ('vp9', 'vp9')], max_length=10, null=True, verbose_name='编码器'),
        ),
        migrations.AlterField(
            model_name='encodeprofile',
            name='description',
            field=models.TextField(blank=True, help_text='description', verbose_name='简介'),
        ),
        migrations.AlterField(
            model_name='encodeprofile',
            name='extension',
            field=models.CharField(choices=[('mp4', 'mp4'), ('webm', 'webm'), ('gif', 'gif')], max_length=10, verbose_name='扩展名'),
        ),
        migrations.AlterField(
            model_name='encodeprofile',
            name='name',
            field=models.CharField(max_length=90, verbose_name='名称'),
        ),
        migrations.AlterField(
            model_name='encodeprofile',
            name='resolution',
            field=models.IntegerField(blank=True, choices=[(2160, '2160'), (1440, '1440'), (1080, '1080'), (720, '720'), (480, '480'), (360, '360'), (240, '240')], null=True, verbose_name='分辨率'),
        ),
        migrations.AlterField(
            model_name='encoding',
            name='add_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='添加日时'),
        ),
        migrations.AlterField(
            model_name='encoding',
            name='chunk',
            field=models.BooleanField(db_index=True, default=False, help_text='是否分片(chunk)?', verbose_name='分片'),
        ),
        migrations.AlterField(
            model_name='encoding',
            name='chunk_file_path',
            field=models.CharField(blank=True, max_length=400, verbose_name='分片文件路径'),
        ),
        migrations.AlterField(
            model_name='encoding',
            name='chunks_info',
            field=models.TextField(blank=True, verbose_name='分片信息'),
        ),
        migrations.AlterField(
            model_name='encoding',
            name='commands',
            field=models.TextField(blank=True, help_text='被执行的命令', verbose_name='命令'),
        ),
        migrations.AlterField(
            model_name='encoding',
            name='logs',
            field=models.TextField(blank=True, verbose_name='日志'),
        ),
        migrations.AlterField(
            model_name='encoding',
            name='md5sum',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='MD5'),
        ),
        migrations.AlterField(
            model_name='encoding',
            name='progress',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='进度'),
        ),
        migrations.AlterField(
            model_name='encoding',
            name='retries',
            field=models.IntegerField(default=0, verbose_name='重试次数'),
        ),
        migrations.AlterField(
            model_name='encoding',
            name='size',
            field=models.CharField(blank=True, max_length=20, verbose_name='大小'),
        ),
        migrations.AlterField(
            model_name='encoding',
            name='status',
            field=models.CharField(choices=[('pending', '等待中'), ('running', '执行中'), ('fail', '执行失败'), ('success', '执行成功')], default='pending', max_length=20, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='encoding',
            name='task_id',
            field=models.CharField(blank=True, max_length=100, verbose_name='任务ID'),
        ),
        migrations.AlterField(
            model_name='encoding',
            name='temp_file',
            field=models.CharField(blank=True, max_length=400, verbose_name='临时文件'),
        ),
        migrations.AlterField(
            model_name='encoding',
            name='total_run_time',
            field=models.IntegerField(default=0, verbose_name='总运行时间'),
        ),
        migrations.AlterField(
            model_name='encoding',
            name='update_date',
            field=models.DateTimeField(auto_now=True, verbose_name='更新日时'),
        ),
        migrations.AlterField(
            model_name='encoding',
            name='worker',
            field=models.CharField(blank=True, max_length=100, verbose_name='Worker'),
        ),
        migrations.AlterField(
            model_name='language',
            name='code',
            field=models.CharField(help_text='语言代号', max_length=12, verbose_name='代号'),
        ),
        migrations.AlterField(
            model_name='language',
            name='title',
            field=models.CharField(help_text='语言标题', max_length=100, verbose_name='标题'),
        ),
        migrations.AlterField(
            model_name='license',
            name='description',
            field=models.TextField(blank=True, verbose_name='简介'),
        ),
        migrations.AlterField(
            model_name='license',
            name='title',
            field=models.CharField(max_length=100, unique=True, verbose_name='标题'),
        ),
        migrations.AlterField(
            model_name='media',
            name='add_date',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='产生日期'),
        ),
        migrations.AlterField(
            model_name='media',
            name='allow_download',
            field=models.BooleanField(default=True, help_text='是否显示下载媒体选项', verbose_name='允许下载'),
        ),
        migrations.AlterField(
            model_name='media',
            name='category',
            field=models.ManyToManyField(blank=True, help_text='媒体可以是一个或多个类别的一部分', to='files.Category'),
        ),
        migrations.AlterField(
            model_name='media',
            name='channel',
            field=models.ForeignKey(blank=True, help_text='媒体可以存在于一个通道中或没有', null=True, on_delete=django.db.models.deletion.CASCADE, to='users.channel'),
        ),
        migrations.AlterField(
            model_name='media',
            name='description',
            field=models.TextField(blank=True, verbose_name='描述'),
        ),
        migrations.AlterField(
            model_name='media',
            name='dislikes',
            field=models.IntegerField(default=0, verbose_name='不喜欢'),
        ),
        migrations.AlterField(
            model_name='media',
            name='duration',
            field=models.IntegerField(default=0, verbose_name='时长'),
        ),
        migrations.AlterField(
            model_name='media',
            name='edit_date',
            field=models.DateTimeField(auto_now=True, verbose_name='编辑日时'),
        ),
        migrations.AlterField(
            model_name='media',
            name='enable_comments',
            field=models.BooleanField(default=True, help_text='是否允许对该媒体发表评论', verbose_name='启用评论'),
        ),
        migrations.AlterField(
            model_name='media',
            name='encoding_status',
            field=models.CharField(choices=[('pending', '等待中'), ('running', '执行中'), ('fail', '执行失败'), ('success', '执行成功')], db_index=True, default='pending', max_length=20, verbose_name='编码状态'),
        ),
        migrations.AlterField(
            model_name='media',
            name='featured',
            field=models.BooleanField(db_index=True, default=False, help_text='是否被编辑全局精选', verbose_name='精选'),
        ),
        migrations.AlterField(
            model_name='media',
            name='friendly_token',
            field=models.CharField(blank=True, db_index=True, help_text='媒体标识符', max_length=12, verbose_name='友善Token'),
        ),
        migrations.AlterField(
            model_name='media',
            name='hls_file',
            field=models.CharField(blank=True, help_text='视频的HLS文件的路径', max_length=1000, verbose_name='HLS文件'),
        ),
        migrations.AlterField(
            model_name='media',
            name='is_reviewed',
            field=models.BooleanField(db_index=True, default=True, help_text='媒体是否经过审查，才能出现在公开列表中', verbose_name='已审查'),
        ),
        migrations.AlterField(
            model_name='media',
            name='likes',
            field=models.IntegerField(db_index=True, default=1, verbose_name='喜欢'),
        ),
        migrations.AlterField(
            model_name='media',
            name='listable',
            field=models.BooleanField(default=False, help_text='是否可以显示在列表', verbose_name='显示在列表'),
        ),
        migrations.AlterField(
            model_name='media',
            name='md5sum',
            field=models.CharField(blank=True, help_text='不外露，内部使用', max_length=50, null=True, verbose_name='MD5'),
        ),
        migrations.AlterField(
            model_name='media',
            name='media_file',
            field=models.FileField(help_text='媒体文件', max_length=500, upload_to=files.models.original_media_file_path, verbose_name='媒体文件'),
        ),
        migrations.AlterField(
            model_name='media',
            name='media_info',
            field=models.TextField(blank=True, help_text='提取的媒体元数据信息', verbose_name='媒体信息'),
        ),
        migrations.AlterField(
            model_name='media',
            name='media_type',
            field=models.CharField(blank=True, choices=[('video', '视频'), ('image', '图片'), ('pdf', 'PDF'), ('audio', '音频')], db_index=True, default='video', max_length=20, verbose_name='媒体类型'),
        ),
        migrations.AlterField(
            model_name='media',
            name='password',
            field=models.CharField(blank=True, help_text='私有媒体密码', max_length=100, verbose_name='密码'),
        ),
        migrations.AlterField(
            model_name='media',
            name='poster',
            field=imagekit.models.fields.ProcessedImageField(blank=True, help_text='媒体提取大缩略图，显示在媒体页', max_length=500, upload_to=files.models.original_thumbnail_file_path, verbose_name='发件人'),
        ),
        migrations.AlterField(
            model_name='media',
            name='preview_file_path',
            field=models.CharField(blank=True, help_text='预览GIF视频，文件系统中的路径', max_length=500, verbose_name='预览文件路径'),
        ),
        migrations.AlterField(
            model_name='media',
            name='rating_category',
            field=models.ManyToManyField(blank=True, help_text='评分类别，如果媒体评分是允许的', to='files.RatingCategory', verbose_name='评分类别'),
        ),
        migrations.AlterField(
            model_name='media',
            name='reported_times',
            field=models.IntegerField(default=0, help_text='媒体被报告了多少次', verbose_name='报告次数'),
        ),
        migrations.AlterField(
            model_name='media',
            name='search',
            field=django.contrib.postgres.search.SearchVectorField(help_text='用于存储媒体的所有可搜索信息和元数据', null=True, verbose_name='搜索'),
        ),
        migrations.AlterField(
            model_name='media',
            name='size',
            field=models.CharField(blank=True, help_text='以字节为单位的媒体大小，自动计算', max_length=20, null=True, verbose_name='大小'),
        ),
        migrations.AlterField(
            model_name='media',
            name='sprites',
            field=models.FileField(blank=True, help_text='精灵文件，仅用于视频，显示在视频播放器', max_length=500, upload_to=files.models.original_thumbnail_file_path, verbose_name='精灵'),
        ),
        migrations.AlterField(
            model_name='media',
            name='state',
            field=models.CharField(choices=[('private', '私有'), ('public', '公开'), ('unlisted', '未加入列表')], db_index=True, default='public', help_text='媒体状态', max_length=20, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='media',
            name='tags',
            field=models.ManyToManyField(blank=True, help_text='从现有标记中选择一个或多个', to='files.Tag'),
        ),
        migrations.AlterField(
            model_name='media',
            name='thumbnail',
            field=imagekit.models.fields.ProcessedImageField(blank=True, help_text='媒体提取小缩略图，显示在列表', max_length=500, upload_to=files.models.original_thumbnail_file_path, verbose_name='缩略图'),
        ),
        migrations.AlterField(
            model_name='media',
            name='thumbnail_time',
            field=models.FloatField(blank=True, help_text='在视频上的时刻，将提取一个缩略图', null=True, verbose_name='缩略图时刻'),
        ),
        migrations.AlterField(
            model_name='media',
            name='title',
            field=models.CharField(blank=True, db_index=True, help_text='媒体标题', max_length=100, verbose_name='标题'),
        ),
        migrations.AlterField(
            model_name='media',
            name='uid',
            field=models.UUIDField(default=uuid.uuid4, help_text='媒体的唯一标识符', unique=True, verbose_name='UUID'),
        ),
        migrations.AlterField(
            model_name='media',
            name='uploaded_poster',
            field=imagekit.models.fields.ProcessedImageField(blank=True, help_text='这张图片将成为媒体的特征', max_length=500, upload_to=files.models.original_thumbnail_file_path, verbose_name='上传图片'),
        ),
        migrations.AlterField(
            model_name='media',
            name='uploaded_thumbnail',
            field=imagekit.models.fields.ProcessedImageField(blank=True, help_text='来自 uploaded_poster 字段的缩略图', max_length=500, upload_to=files.models.original_thumbnail_file_path, verbose_name='上传的缩略图'),
        ),
        migrations.AlterField(
            model_name='media',
            name='user',
            field=models.ForeignKey(help_text='上传媒体的用户', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='media',
            name='user_featured',
            field=models.BooleanField(default=False, help_text='被用户精选', verbose_name='用户精选'),
        ),
        migrations.AlterField(
            model_name='media',
            name='video_height',
            field=models.IntegerField(default=1, verbose_name='视频高'),
        ),
        migrations.AlterField(
            model_name='media',
            name='views',
            field=models.IntegerField(db_index=True, default=1, verbose_name='查看'),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='add_date',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='添加日时'),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='description',
            field=models.TextField(blank=True, help_text='description', verbose_name='简介'),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='friendly_token',
            field=models.CharField(blank=True, db_index=True, max_length=12, verbose_name='友善Token'),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='title',
            field=models.CharField(db_index=True, max_length=100, verbose_name='标题'),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='uid',
            field=models.UUIDField(default=uuid.uuid4, unique=True, verbose_name='UUID'),
        ),
        migrations.AlterField(
            model_name='playlistmedia',
            name='action_date',
            field=models.DateTimeField(auto_now=True, verbose_name='启用日时'),
        ),
        migrations.AlterField(
            model_name='playlistmedia',
            name='ordering',
            field=models.IntegerField(default=1, verbose_name='排序'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='add_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='添加日期'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='score',
            field=models.IntegerField(validators=[files.models.validate_rating], verbose_name='评分'),
        ),
        migrations.AlterField(
            model_name='ratingcategory',
            name='description',
            field=models.TextField(blank=True, verbose_name='简介'),
        ),
        migrations.AlterField(
            model_name='ratingcategory',
            name='enabled',
            field=models.BooleanField(default=True, verbose_name='启用的'),
        ),
        migrations.AlterField(
            model_name='ratingcategory',
            name='title',
            field=models.CharField(db_index=True, max_length=200, unique=True, verbose_name='标题'),
        ),
        migrations.AlterField(
            model_name='subtitle',
            name='subtitle_file',
            field=models.FileField(help_text='File has to be WebVTT format', max_length=500, upload_to=files.models.subtitles_file_path, verbose_name='字幕/CC文件'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='listings_thumbnail',
            field=models.CharField(blank=True, db_index=True, help_text='Thumbnail to show on listings', max_length=400, null=True, verbose_name='列表缩略图'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='media_count',
            field=models.IntegerField(default=0, help_text='number of media', verbose_name='媒体数量'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='title',
            field=models.CharField(db_index=True, max_length=100, unique=True, verbose_name='标题'),
        ),
    ]
