# Generated by Django 3.1.12 on 2021-09-01 02:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('files', '0004_auto_20210901_0819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='media',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='files.media', verbose_name='媒体'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
        migrations.AlterField(
            model_name='encoding',
            name='media',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='encodings', to='files.media', verbose_name='媒体'),
        ),
        migrations.AlterField(
            model_name='encoding',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='files.encodeprofile', verbose_name='个人信息'),
        ),
        migrations.AlterField(
            model_name='media',
            name='category',
            field=models.ManyToManyField(blank=True, help_text='媒体可以是一个或多个类别的一部分', to='files.Category', verbose_name='分类'),
        ),
        migrations.AlterField(
            model_name='media',
            name='user',
            field=models.ForeignKey(help_text='上传媒体的用户', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playlists', to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
        migrations.AlterField(
            model_name='playlistmedia',
            name='media',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='files.media', verbose_name='媒体'),
        ),
        migrations.AlterField(
            model_name='playlistmedia',
            name='playlist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='files.playlist', verbose_name='播放列表'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='media',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='files.media', verbose_name='媒体'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='rating_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='files.ratingcategory', verbose_name='评分类型'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
        migrations.AlterField(
            model_name='subtitle',
            name='language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='files.language', verbose_name='语言'),
        ),
        migrations.AlterField(
            model_name='subtitle',
            name='media',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subtitles', to='files.media', verbose_name='媒体'),
        ),
        migrations.AlterField(
            model_name='subtitle',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
    ]
